########################################################################################################################
# Скрипты общего назначения
########################################################################################################################

- script: confirm_next
  body: У него есть уши?
  positive: confirm
  negative: negative

- script: negative
  body: Это хлеб, а не кот! Ешь его!

- script: confirm
  body: Это кот, а не хлеб! Не ешь его!

- script: negative_confirm
  body: Это кот, а не хлеб! Не ешь его!

- script: final
  body: у меня нет вопроссов!


########################################################################################################################
# Основной сценарий для бота
########################################################################################################################

- script: main
  body: Привет! Я могу отличить кота от хлеба! ОбЪект перед тобой квадратный?
  positive: confirm_next
  negative: negative_confirm
