########################################################################################################################
# Скрипты общего назначения
########################################################################################################################

- script: feedback_close_dialog
  button: Да
  body: Был рад вам помочь 😊

- script: to_operator
  button: Нет
  body: Ваш диалог передан оператору


########################################################################################################################
# Основной сценарий для бота
########################################################################################################################

- script: main
  body: Привет! Я могу отличить кота от хлеба!

