version: '3.7'

services:

  # ####################################################################################################################
  # Веб-сервисы (backend)
  # ####################################################################################################################
  backend:
    depends_on:
      - psql
    ports:
      - $BACKEND_EXT_PORT:8000

  # ####################################################################################################################
  # Системные службы (базы данных, очереди, кеши)
  # ####################################################################################################################
  psql:
    image: postgres:12.1-alpine
    expose:
      - 5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PSQL_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  psql_data: {}
 
